{% set name = "cuda-nvdisasm" %}
{% set version = "13.4.49" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set sha256 = "622619236e0965fdb7a4407d5899afd1560c6f26e9d06a16cdeb2fe58af2e1f8" %}  # [linux64]
{% set sha256 = "0b50c279dadd8abdaeae1f98d0ceaf3c3bb2ef4a9e314c287468ab828d35b423" %}  # [aarch64]
{% set sha256 = "462f63933a4c60961e5f5fd5d1221d0f3b5a69f63115e12361d207a2927a821d" %}  # [win64]
{% set sha256 = "24d5028ecb62c9cca2a0f2ae6766762bae68d292bdcd8fe64961044638c16c94" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/{{ platform }}/cuda_nvdisasm-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]
  script:
    - move bin\* %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - patchelf                                        # [linux]
  files:
    - test-rpath.sh                                   # [linux]
  commands:
    - test -f $PREFIX/bin/nvdisasm                    # [linux]
    - bash test-rpath.sh                              # [linux]
    - if not exist %LIBRARY_BIN%\nvdisasm.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: nvdisasm extracts information from standalone cubin files
  description: |
    nvdisasm extracts information from standalone cubin files and presents them in
    human readable format.
  doc_url: https://docs.nvidia.com/cuda/cuda-binary-utilities/

extra:
  recipe-maintainers:
    - conda-forge/cuda
