{% set name = "cuda-nvdisasm" %}
{% set version = "13.2.78" %}
{% set cuda_version = "13.2" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/{{ platform }}/cuda_nvdisasm-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 4a09184fe49bf9825cc21f0e7fa2133a0eeb75a85b125671ac40acb3fe1150d6  # [linux64]
  sha256: 0917e7291f41b6a32b5350e5c5e6f80ae8ca873a2504a0e9b2233b74bafe5cae  # [aarch64]
  sha256: 6fa14f9f0a4c6ac85cc1ed07d412c05100f2e9a89860857ef0b04e0fc25945b1  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]
  script:
    - move bin\* %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - patchelf                                        # [linux]
  files:
    - test-rpath.sh                                   # [linux]
  commands:
    - test -f $PREFIX/bin/nvdisasm                    # [linux]
    - bash test-rpath.sh                              # [linux]
    - if not exist %LIBRARY_BIN%\nvdisasm.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: nvdisasm extracts information from standalone cubin files
  description: |
    nvdisasm extracts information from standalone cubin files and presents them in
    human readable format.
  doc_url: https://docs.nvidia.com/cuda/cuda-binary-utilities/

extra:
  recipe-maintainers:
    - conda-forge/cuda
